// import './example/basic-type'
// import './example/basic-symbol'
// import './example/Interface' 
// import './example/function'
// import './example/generic'
// import './example/class/base-class1'
// import './example/class/base-class2'
import './example/class/class'